models/usuario.py
from mailbox import NoSuchMailboxError
from utils.db import db

class Usuario(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    nombre = db.Column(db.String(45))
    apellido = db.Column(db.String(45))
    username = db.Column(db.String(45))
    password = db.Column(db.String(45))
    

    def __init__(self, nombre, apellido, username, password):
        self.nombre
        self.apellido
        self.username
        self.password

app.py
from flask import Flask
from routes.usuarios import usuarios
from flask_sqlalchemy import SQLAlchemy
from config import DATABASE_CONNECTION_URI

app = Flask(__name__)

app.secret_key = "secret key"
app.config['SQLALCHEMY_DATABASE_URI'] = DATABASE_CONNECTION_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

SQLAlchemy(app)

app.register_blueprint(usuarios)

routes/usuarios.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.usuario import Usuario
from utils.db import db

usuarios = Blueprint('usuarios', __name__)

@usuarios.route('/')
def index():
    usuarios = Usuario.query.all()
    return render_template('index.html', usuarios = usuarios)


@usuarios.route('/new', methods = ['POST'])
def add_user():
    nombre = request.form['nombre']
    apellido = request.form['apellido']
    username = request.form['username']
    password = request.form['password']
    
    new_usuario = Usuario(nombre, apellido, username, password)
    
    db.session.add(new_usuario)
    db.session.commit()
    
    flash("Usuario agregado satisfactoriamente.")
    
    return redirect(url_for('usuarios.index'))


@usuarios.route('/update/<id>', methods = ['POST', 'GET'])
def update_user(id):
    usuario = Usuario.query.get(id)
    
    if request.method == "POST":
        usuario.nombre = request.form['nombre']
        usuario.apellido = request.form['apellido']
        usuario.username = request.form['username']
        usuario.password = request.form['password']
        
        db.session.commit()
        
        flash("Usuario actualizado satisfactoriamente.")
        
        return redirect(url_for("usuarios.index"))
        
    return render_template('update_user.html', usuario = usuario)


@usuarios.route('/delete/<id>')
def delete_user(id):
    usuario = Usuario.query.get(id)
    db.session.delete(usuario)
    db.session.commit()
    
    flash("Usuario eliminado satisfactoriamente.")
    
    return redirect(url_for('usuarios.index'))


@usuarios.route('/about')
def about():
    return render_template('about.html')

templates/about.html
{% extends 'layout.html' %}

{% block body %}

<h1>About</h1>

<p>Lorem ipsum dolor sit amet. In mollitia possimus est sunt praesentium ut dolores dolorem 33 voluptates quaerat. 33 dolorem soluta sit galisum dolorum aut rerum vero sed nisi quasi! Qui voluptatem praesentium a itaque velit non deleniti soluta et rerum neque est ducimus quas ex nemo repudiandae id voluptate vitae.

    Id fuga sunt est atque odit qui similique voluptas a minima accusamus aut beatae quibusdam nam facere tenetur qui distinctio. Ex voluptatem fugit in quod fugiat ut nihil repellat. At rerum provident qui nihil officia et voluptas nihil! Ea facere quo distinctio rerum ut sint veniam.
    
    Et iure recusandae ut ipsum soluta qui beatae sapiente in animi ipsam qui molestiae sapiente aut voluptatem doloremque nam dicta numquam. Qui nihil vitae eum debitis nihil ut vitae beatae ut perferendis consectetur. In similique autem sed consequatur officiis et veritatis iste sed laborum tempore qui labore nesciunt aut voluptatem enim.
</p>

{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block body %}

<div class = "row">
    <div class = "col-md-5">
        {% include 'partials/_userForm.html' %}

        {% include 'partials/_messages.html' %}
    </div>

    <div class = "col-md-7">
        {% for usuario in usuarios %}

        <div class = "card mb-1 text-white bg-dark">
            <div class = "card-body">
                <div class = "d-flex justify-content-between">
                    <h5>{{usuario.nombre}} {{usuario.apellido}}</h5>                 
                    <div>
                        <a href = "{{url_for('usuarios.update_user', id = usuario.id)}}" class = "btn btn-warning btn-sm">Actualizar</a>
                        <a href = "{{url_for('usuarios.delete_user', id = usuario.id)}}" class = "btn btn-danger btn-sm">Eliminar</a>
                    </div>
                </div>
                <p>{{usuario.username}}</p>
                <p>{{usuario.password}}</p> 
            </div>             
        </div>     
        {% endfor %}
    </div>

</div>    

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang = "en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD Usuario</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel = "stylesheet" href = "{{url_for('static', filename = 'css/main.css')}}"
</head>
<body>
    {% include('partials/_navbar.html')%}

    <div class = "container p-2">
        {% block body %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
</body>
</html>

templates/partials/_messages.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{message}}            
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div> 
        {% endfor %}
    {% endif %}
{% endwith %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">CRUD Usuario</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href = "/about">Sobre</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/partials/_userForm.html
<form action = "/new" method = "POST" class = "card bg-dark text-light">
    <div class = "card-body p-4">
        <div class = "mb-3">
            <label for = "nombre" class = "mb-3">Nombre:</label>
            <input type = "text" name = "nombre" placeholder = "Escribe tu nombre" class = "form-control rounded-5 bg-dark border-0 text-white"/> 
        </div>
        <div class = "mb-3">
            <label for = "apellido" class = "mb-3">Apellido:</label>
            <input type = "text" name = "apellido" placeholder = "Escribe tu apellido" class = "form-control rounded-5 bg-dark border-0 text-white"/>        
        </div>
        <div class = "mb-3">
            <label for = "username" class = "mb-3">Nombre de usuario:</label>
            <input type = "text" name = "username" placeholder = "Escribe tu nombre de usuario" class = "form-control rounded-5 bg-dark border-0 text-white"/>        
        </div>
        <div class = "mb-3">
            <label for = "password" class = "mb-3">Contraseña:</label>
            <input type = "password" name = "password" placeholder = "Escribe tu contraseña" class = "form-control rounded-5 bg-dark border-0 text-white"/> 
        </div>
        <div class="d-grid gap-2 col-4 mx-auto mt-4 mb-3">
            <button class = "btn btn-primary">Guardar</button>
        </div>
    </div>
</form>

templates/update_user.html
{% extends 'layout.html' %}

{% block body %}

<div class = "row">
    <div class = "col-md-4 offset-md-4">
        <form action = "/update/{{usuario.id}}" method = "POST" class = "card bg-dark text-light">
            <div class = "card-body p-4">
                <div class = "mb-3">
                    <label for = "nombre" class = "mb-3">Nombre:</label>
                    <input type = "text" name = "nombre" placeholder = "Escribe tu nombre" value = "{{usuario.nombre}}" class = "form-control rounded-5 bg-dark border-0 text-white"/> 
                </div>
                <div class = "mb-3">
                    <label for = "apellido" class = "mb-3">Apellido:</label>
                    <input type = "text" name = "apellido" placeholder = "Escribe tu apellido" value = "{{usuario.apellido}}" class = "form-control rounded-5 bg-dark border-0 text-white"/>        
                </div>
                <div class = "mb-3">
                    <label for = "username" class = "mb-3">Nombre de usuario:</label>
                    <input type = "text" name = "username" placeholder = "Escribe tu nombre de usuario" value = "{{usuario.username}}" class = "form-control rounded-5 bg-dark border-0 text-white"/>        
                </div>
                <div class = "mb-3">
                    <label for = "password" class = "mb-3">Contraseña:</label>
                    <input type = "password" name = "password" placeholder = "Escribe tu contraseña" value = "{{usuario.password}}" class = "form-control rounded-5 bg-dark border-0 text-white"/> 
                </div>
                <div class="d-grid gap-2 col-4 mx-auto mt-4 mb-3">
                    <button class = "btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}